### PR TITLE
Remove vertx openapi

### LINKED ISSUE #772: Startup failure
When starting up web3signer, after loading keys, the service may stop with the following stacktrace:
```
2023-04-19 22:17:04.667+00:00 | main | ERROR | Runner | Failed to initialise application
java.util.concurrent.ExecutionException: io.vertx.ext.web.openapi.RouterBuilderException: Cannot load the spec in path file:///tmp/w3s_openapi_17095143643154225637/eth2/web3signer.yaml
    at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
    at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
    at tech.pegasys.web3signer.core.Runner.getRouterBuilder(Runner.java:232) ~[web3signer-core-23.3.1.jar:23.3.1]
    at tech.pegasys.web3signer.core.Runner.run(Runner.java:138) ~[web3signer-core-23.3.1.jar:23.3.1]
    at tech.pegasys.web3signer.core.Eth2Runner.run(Eth2Runner.java:375) ~[web3signer-core-23.3.1.jar:23.3.1]
    at tech.pegasys.web3signer.commandline.subcommands.ModeSubCommand.run(ModeSubCommand.java:28) ~[web3signer-commandline-23.3.1.jar:23.3.1]
    at picocli.CommandLine.executeUserObject(CommandLine.java:1939) ~[picocli-4.6.2.jar:4.6.2]
    at picocli.CommandLine.access$1300(CommandLine.java:145) ~[picocli-4.6.2.jar:4.6.2]
    at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358) ~[picocli-4.6.2.jar:4.6.2]
    at picocli.CommandLine$RunLast.handle(CommandLine.java:2352) ~[picocli-4.6.2.jar:4.6.2]
Caused by: io.vertx.ext.web.openapi.RouterBuilderException: Cannot load the spec in path file:///tmp/w3s_openapi_17095143643154225637/eth2/web3signer.yaml
    at io.vertx.ext.web.openapi.RouterBuilderException.createInvalidSpecFile(RouterBuilderException.java:50) ~[vertx-web-openapi-4.3.8.jar:4.3.8]
    at io.vertx.ext.web.openapi.RouterBuilder.lambda$create$0(RouterBuilder.java:243) ~[vertx-web-openapi-4.3.8.jar:4.3.8]
    at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153) ~[vertx-core-4.3.8.jar:4.3.8]
    at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75) ~[vertx-core-4.3.8.jar:4.3.8]
    at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230) ~[vertx-core-4.3.8.jar:4.3.8]
    at io.vertx.core.impl.future.Composition$1.onFailure(Composition.java:66) ~[vertx-core-4.3.8.jar:4.3.8]
    at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75) ~[vertx-core-4.3.8.jar:4.3.8]
    at io.vertx.core.impl.future.FailedFuture.addListener(FailedFuture.java:98) ~[vertx-core-4.3.8.jar:4.3.8]
    at io.vertx.core.impl.future.Composition.onFailure(Composition.java:55) ~[vertx-core-4.3.8.jar:4.3.8]
    at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75) ~[vertx-core-4.3.8.jar:4.3.8]
Caused by: java.lang.IllegalStateException: Recursive update
    at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1763) ~[?:?]
    at io.vertx.ext.web.openapi.impl.OpenAPIHolderImpl.resolveExternalRef(OpenAPIHolderImpl.java:267) ~[vertx-web-openapi-4.3.8.jar:4.3.8]
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
    at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707) ~[?:?]
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
    at io.vertx.ext.web.openapi.impl.OpenAPIHolderImpl.walkAndSolve(OpenAPIHolderImpl.java:208) ~[vertx-web-openapi-4.3.8.jar:4.3.8]
  ```

### PR DESCRIPTION
**Pull request by jframe**
## PR Description
Remove the usage of the Vertx openAPI module to workaround bug in Vertx openAPI module. There are also restrictions on the open API spec that the module supports.

## Fixed Issue(s)

fixes #772

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: core/src/main/java/tech/pegasys/web3signer/core/Eth1Runner.java [hunk 1]
```diff
@@ -74,23 +69,18 @@ public Eth1Runner(final BaseConfig baseConfig, final Eth1Config eth1Config) {
...
-  protected Router populateRouter(final Context context) {
-    final RouterBuilder routerBuilder = context.getRouterBuilder();
+  protected void populateRouter(final Context context) {
+    final Router router = context.getRouter();
     final LogErrorHandler errorHandler = context.getErrorHandler();
     final ArtifactSignerProvider signerProvider = context.getArtifactSignerProvider();
 
     addPublicKeysListHandler(
-        routerBuilder, signerProvider, ETH1_LIST.name(), context.getErrorHandler());
+        router, signerProvider, "/api/v1/eth1/publicKeys", context.getErrorHandler());
```
Comment (usmansaleem) [inline core/src/main/java/tech/pegasys/web3signer/core/Eth1Runner.java:78]: it might be a good idea to create an interface, may be `Eth1Routes`, `Eth2Routes`, that list all the constants for the route paths.

File: core/src/main/java/tech/pegasys/web3signer/core/Eth2Runner.java [hunk 2]
```diff
@@ -136,49 +130,35 @@ private Optional<SlashingProtectionContext> createSlashingProtection(
     }
   }
 
-  @Override
-  protected String getOpenApiSpecResource() {
-    return "eth2/web3signer.yaml";
-  }
+  //  @Override
```
Comment (usmansaleem) [inline core/src/main/java/tech/pegasys/web3signer/core/Eth2Runner.java:133]: commented code should be removed.

File: core/src/main/java/tech/pegasys/web3signer/core/service/http/handlers/signing/eth2/Eth2SignForIdentifierHandler.java [hunk 3]
```diff
@@ -386,8 +384,8 @@ private String getAcceptableContentType(final List<MIMEHeader> mimeHeaders) {
   }
 
   private boolean isJsonCompatibleHeader(final MIMEHeader mimeHeader) {
-    final String mimeComponent = mimeHeader.component() + "/" + mimeHeader.subComponent();
-    return Objects.equals("application/json", mimeComponent)
-        || Objects.equals("*/*", mimeComponent);
+    final String mimeType =
+        mimeHeader.value(); // Must use value() rather than component() to ensure header is parsed
+    return Objects.equals("application/json", mimeType) || Objects.equals("*/*", mimeType);
```
Comment (usmansaleem) [inline core/src/main/java/tech/pegasys/web3signer/core/service/http/handlers/signing/eth2/Eth2SignForIdentifierHandler.java:389]: we may be able to enhance it by using `"application/json".equalsIgnoreCase(mimeType)"` to cover upper/lower or mixed case headers.

File: core/src/test/java/tech/pegasys/web3signer/core/util/OpenApiSpecsExtractorTest.java [hunk 4]
```diff
@@ -13,43 +13,26 @@
...
 import org.junit.jupiter.params.provider.ValueSource;
 
-@ExtendWith(VertxExtension.class)
 class OpenApiSpecsExtractorTest {
 
   @ParameterizedTest
   @ValueSource(
       strings = {"eth1/web3signer.yaml", "eth2/web3signer.yaml", "filecoin/web3signer.yaml"})
-  void openapiSpecsAreExtractedAndLoaded(final String spec, final Vertx vertx) throws Exception {
+  void openapiSpecsAreExtractedAndLoaded(final String spec) throws Exception {
```
Comment (usmansaleem) [inline core/src/test/java/tech/pegasys/web3signer/core/util/OpenApiSpecsExtractorTest.java:31]: I think we should be able to remove OpenApiSpecsExtractor class and its usage as the whole reason was to modify the paths in the openapi spec so that it is readable by the parser.

**Review by usmansaleem — APPROVED** [review]
LGTM - few comments.

File: core/src/main/java/tech/pegasys/web3signer/core/service/http/handlers/signing/eth2/Eth2SignForIdentifierHandler.java (hunk 3 above)
Comment (jframe) [reply core/src/main/java/tech/pegasys/web3signer/core/service/http/handlers/signing/eth2/Eth2SignForIdentifierHandler.java:389]: done

File: core/src/test/java/tech/pegasys/web3signer/core/util/OpenApiSpecsExtractorTest.java (hunk 4 above)
Comment (jframe) [reply core/src/test/java/tech/pegasys/web3signer/core/util/OpenApiSpecsExtractorTest.java:31]: Wasn't able to remove it, it's still needed to copy the files from the jar to the filesystem so we can serve the static content for the swagger UI

File: core/src/main/java/tech/pegasys/web3signer/core/Eth1Runner.java (hunk 1 above)
Comment (jframe) [reply core/src/main/java/tech/pegasys/web3signer/core/Eth1Runner.java]: extracted some constants to the runners
