### PR TITLE
fix: Make cached GVR thread-safe

### LINKED ISSUE #978: ERROR:  duplicate key value violates unique constraint "metadata_pkey"
ERROR:  duplicate key value violates unique constraint "metadata_pkey : This error is occurring after starting postgres container . We are facing this issue after upgrading to postgres:14.9 from postgres:12. The data from previous version has been deleted before starting the new version.

Web3signer or teku validator client does not show any errors during this timestamp. No attestations are missed. 

We are getting this error when postgres is initiated. Log file is attached below

[postgres_logs.txt](https://github.com/Consensys/web3signer/files/14540172/postgres_logs.txt)

### PR DESCRIPTION
**Pull request by usmansaleem**
## PR Description
Make cached GVR calculation thread-safe. During Web3Signer first boot, if multiple requests for signing comes in, it can result in multiple threads attempting to insert gvr in a fresh database. This would show an constraint violation in database logs.

## Fixed Issue(s)

Fixes #978 
## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

## Testing

- [x] I thought about testing these changes in a realistic/non-local environment.

### CODE REVIEW

File: slashing-protection/src/main/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidator.java [hunk 1]
```diff
@@ -65,6 +60,30 @@ public boolean checkGenesisValidatorsRootAndInsertIfEmpty(final Bytes32 genesisV
     }
   }
 
+  private Bytes32 insertAndCacheGVR(final Bytes32 genesisValidatorsRoot) {
+    var cachedGVR = cachedGVRRef.get();
+    if (cachedGVR == null) {
+      LOG.debug("No cached GVR found, fetching from database");
+      synchronized (lockForCachedGVR) {
```
Comment (jframe) [inline slashing-protection/src/main/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidator.java:67]: Can one of the AtomicReference atomic operations be used to update the value to avoid the synchronized block?

File: slashing-protection/src/main/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidator.java [hunk 2]
```diff
@@ -36,7 +37,8 @@ public class GenesisValidatorRootValidator {
   private final MetadataDao metadataDao;
   private final FailsafeExecutor<Object> failsafeExecutor;
 
-  private Bytes32 cachedGenesisValidatorRoot;
+  private final AtomicReference<Bytes32> cachedGVRRef = new AtomicReference<>();
```
Comment (jframe) [inline slashing-protection/src/main/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidator.java:40]: Looks like we are using our cache, think it would be better to use the Guava cache rather than writing our thread safe implementation

Comment (usmansaleem) [reply slashing-protection/src/main/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidator.java:40]: Hmm, correct. Guava Cache would achieve the same result.

File: slashing-protection/src/test/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidatorTest.java [hunk 3]
```diff
@@ -64,6 +69,39 @@ void verifyCachedGVRIsUsedForNewGVR(final Jdbi jdbi) {
...
+            } finally {
+              latch.countDown(); // Ensure the latch is counted down even if an exception is thrown
+            }
+          });
+    }
+
+    latch.await(); // Wait for all threads to finish
+    executorService.shutdown(); // Shutdown the executor service
+
+    assertThat(allTrue.get()).isTrue();
```
Comment (siladu) [inline slashing-protection/src/test/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidatorTest.java:100]: Don't think this check or the latch is doing anything. 

When this fails, it's due to the number of times findGenesisValidatorsRoot is called

File: slashing-protection/src/main/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidator.java (hunk 2 above)
Comment (siladu) [reply slashing-protection/src/main/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidator.java:40]: or ConcurrentHashMap?

File: slashing-protection/src/test/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidatorTest.java (hunk 3 above)
Comment (usmansaleem) [reply slashing-protection/src/test/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidatorTest.java:100]: `latch.await();` to make sure that all threads have joined. Agreed with allTrue. I added findByGVR assertions later on :). Will be removing allTrue assertion.

Comment (usmansaleem) [reply slashing-protection/src/test/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidatorTest.java]: decided to rename allTrue and still kept it.

File: slashing-protection/src/test/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidatorTest.java [hunk 4]
```diff
@@ -64,6 +68,36 @@ void verifyCachedGVRIsUsedForNewGVR(final Jdbi jdbi) {
...
+              allCachedGVRMatches.set(false);
+            }
+          });
+    }
+
+    // Shutdown the executor service, no new tasks will be accepted
+    executorService.shutdown();
+
+    // wait for all threads to finish
+    var successfulTerminate = executorService.awaitTermination(5, MINUTES);
```
Comment (siladu) [inline slashing-protection/src/test/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidatorTest.java:93]: Could probably even make this SECONDS so we don't slow down the tests too much if this were to happen

**Review by siladu — APPROVED** [review]
LGTM

File: slashing-protection/src/test/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidatorTest.java (hunk 4 above)
Comment (usmansaleem) [reply slashing-protection/src/test/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidatorTest.java]: Reduced it to 1 minute.
