### PR TITLE
Cache gvr in-memory

### LINKED ISSUE #600: Cache GVR from DB
Cache GVR stored in the database as this value doesn't change once set.

### LINKED ISSUE #798: Thread blocked error
Web3signer version _web3signer/v23.3.1/linux-x86_64/-eclipseadoptium-openjdk64bitservervm-java-17_
On 6 june 2023 (UTC), we have issues signing on mainnet due to a thread problem with web3signer. This issue persisted for 1 minute and 9 seconds. The following are the initial logs which kept repeating until the problem resolved itself. 

I'm attaching the Grafana logs for your reference.

```
web3signer_latest  | 2023-06-06 23:21:39.805+00:00 | vertx-blocked-thread-checker | WARN  | BlockedThreadChecker | Thread Thread[vert.x-worker-thread-19,5,main] has been blocked for 60747 ms, time limit is 60000 ms
web3signer_latest  | io.vertx.core.VertxException: Thread blocked
web3signer_latest  |    at sun.nio.ch.Net.poll(Native Method) ~[?:?]
web3signer_latest  |    at sun.nio.ch.NioSocketImpl.park(Unknown Source) ~[?:?]
web3signer_latest  |    at sun.nio.ch.NioSocketImpl.timedRead(Unknown Source) ~[?:?]
web3signer_latest  |    at sun.nio.ch.NioSocketImpl.implRead(Unknown Source) ~[?:?]
web3signer_latest  |    at sun.nio.ch.NioSocketImpl.read(Unknown Source) ~[?:?]
web3signer_latest  |    at sun.nio.ch.NioSocketImpl$1.read(Unknown Source) ~[?:?]
web3signer_latest  |    at java.net.Socket$SocketInputStream.read(Unknown Source) ~[?:?]
web3signer_latest  |    at sun.security.ssl.SSLSocketInputRecord.read(Unknown Source) ~[?:?]
web3signer_latest  |    at sun.security.ssl.SSLSocketInputRecord.readHeader(Unknown Source) ~[?:?]
web3signer_latest  |    at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(Unknown Source) ~[?:?]
web3signer_latest  |    at sun.security.ssl.SSLSocketImpl.readApplicationRecord(Unknown Source) ~[?:?]
web3signer_latest  |    at sun.security.ssl.SSLSocketImpl$AppInputStream.read(Unknown Source) ~[?:?]
web3signer_latest  |    at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:161) ~[postgresql-42.5.3.jar:42.5.3]
web3signer_latest  |    at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:128) ~[postgresql-42.5.3.jar:42.5.3]
web3signer_latest  |    at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:113) ~[postgresql-42.5.3.jar:42.5.3]
web3signer_latest  |    at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:73) ~[postgresql-42.5.3.jar:42.5.3]
web3signer_latest  |    at org.postgresql.core.PGStream.receiveChar(PGStream.java:465) ~[postgresql-42.5.3.jar:42.5.3]
web3signer_latest  |    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2120) ~[postgresql-42.5.3.jar:42.5.3]
web3signer_latest  |    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356) ~[postgresql-42.5.3.jar:42.5.3]
web3signer_latest  |    at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496) ~[postgresql-42.5.3.jar:42.5.3]
web3signer_latest  |    at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413) ~[postgresql-42.5.3.jar:42.5.3]
web3signer_latest  |    at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190) ~[postgresql-42.5.3.jar:42.5.3]
web3signer_latest  |    at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:177) ~[postgresql-42.5.3.jar:42.5.3]
web3signer_latest  |    at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[HikariCP-5.0.1.jar:?]
web3signer_latest  |    at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) ~[HikariCP-5.0.1.jar:?]
web3signer_latest  |    at org.jdbi.v3.core.statement.SqlStatement$$Lambda$554/0x00000008004c7828.invoke(Unknown Source) ~[?:?]
web3signer_latest  |    at org.jdbi.v3.core.statement.SqlLoggerUtil.wrap(SqlLoggerUtil.java:31) ~[jdbi3-core-3.36.0.jar:3.36.0]
web3signer_latest  |    at org.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1787) ~[jdbi3-core-3.36.0.jar:3.36.0]
web3signer_latest  |    at org.jdbi.v3.core.statement.Query$$Lambda$522/0x00000008004aa3b8.get(Unknown Source) ~[?:?]
web3signer_latest  |    at org.jdbi.v3.core.result.ResultProducers.lambda$createResultBearing$3(ResultProducers.java:94) ~[jdbi3-core-3.36.0.jar:3.36.0]
web3signer_latest  |    at org.jdbi.v3.core.result.ResultProducers$$Lambda$524/0x00000008004aaa00.get(Unknown Source) ~[?:?]
web3signer_latest  |    at org.jdbi.v3.core.result.ResultIterable.lambda$of$0(ResultIterable.java:58) ~[jdbi3-core-3.36.0.jar:3.36.0]
web3signer_latest  |    at org.jdbi.v3.core.result.ResultIterable$$Lambda$541/0x00000008004ae2c8.iterator(Unknown Source) ~[?:?]
web3signer_latest  |    at org.jdbi.v3.core.result.ResultIterable.findFirst(ResultIterable.java:244) ~[jdbi3-core-3.36.0.jar:3.36.0]
web3signer_latest  |    at tech.pegasys.web3signer.slashingprotection.dao.MetadataDao.findGenesisValidatorsRoot(MetadataDao.java:28) ~[web3signer-slashing-protection-23.3.1.jar:23.3.1]
web3signer_latest  |    at tech.pegasys.web3signer.slashingprotection.validator.GenesisValidatorRootValidator.validateGvr(GenesisValidatorRootValidator.java:61) ~[web3signer-slashing-protection-23.3.1.jar:23.3.1]
web3signer_latest  |    at tech.pegasys.web3signer.slashingprotection.validator.GenesisValidatorRootValidator.lambda$checkGenesisValidatorsRootAndInsertIfEmpty$0(GenesisValidatorRootValidator.java:49) ~[web3signer-slashing-protection-23.3.1.jar:23.3.1]
web3signer_latest  |    at tech.pegasys.web3signer.slashingprotection.validator.GenesisValidatorRootValidator$$Lambda$1138/0x000000080076b348.withHandle(Unknown Source) ~[?:?]
web3signer_latest  |    at org.jdbi.v3.core.transaction.LocalTransactionHandler$BoundLocalTransactionHandler.inTransaction(LocalTransactionHandler.java:208) ~[jdbi3-core-3.36.0.jar:3.36.0]
web3signer_latest  |    at org.jdbi.v3.core.transaction.SerializableTransactionRunner.inTransaction(SerializableTransactionRunner.java:55) ~[jdbi3-core-3.36.0.jar:3.36.0]
web3signer_latest  |    at org.jdbi.v3.core.transaction.SerializableTransactionRunner.inTransaction(SerializableTransactionRunner.java:89) ~[jdbi3-core-3.36.0.jar:3.36.0]
web3signer_latest  |    at org.jdbi.v3.core.Handle.inTransaction(Handle.java:768) ~[jdbi3-core-3.36.0.jar:3.36.0]
web3signer_latest  |    at org.jdbi.v3.core.Jdbi.lambda$inTransaction$7(Jdbi.java:441) ~[jdbi3-core-3.36.0.jar:3.36.0]
web3signer_latest  |    at org.jdbi.v3.core.Jdbi$$Lambda$872/0x00000008006a2b60.withHandle(Unknown Source) ~[?:?]
web3signer_latest  |    at org.jdbi.v3.core.Jdbi.withHandle(Jdbi.java:367) ~[jdbi3-core-3.36.0.jar:3.36.0]
web3signer_latest  |    at org.jdbi.v3.core.Jdbi.inTransaction(Jdbi.java:441) ~[jdbi3-core-3.36.0.jar:3.36.0]
web3signer_latest  |    at tech.pegasys.web3signer.slashingprotection.validator.GenesisValidatorRootValidator.lambda$checkGenesisValidatorsRootAndInsertIfEmpty$1(GenesisValidatorRootValidator.java:48) ~[web3signer-slashing-protection-23.3.1.jar:23.3.1]
web3signer_latest  |    at tech.pegasys.web3signer.slashingprotection.validator.GenesisValidatorRootValidator$$Lambda$1130/0x0000000800769b40.get(Unknown Source) ~[?:?]
web3signer_latest  |    at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:48) ~[failsafe-2.4.4.jar:2.4.4]
web3signer_latest  |    at net.jodah.failsafe.Functions$$Lambda$1134/0x000000080076aaa8.get(Unknown Source) ~[?:?]
web3signer_latest  |    at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66) ~[failsafe-2.4.4.jar:2.4.4]
web3signer_latest  |    at net.jodah.failsafe.RetryPolicyExecutor$$Lambda$1136/0x000000080076aef8.get(Unknown Source) ~[?:?]
web3signer_latest  |    at net.jodah.failsafe.Execution.executeSync(Execution.java:128) ~[failsafe-2.4.4.jar:2.4.4]
web3signer_latest  |    at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:379) ~[failsafe-2.4.4.jar:2.4.4]
web3signer_latest  |    at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:68) ~[failsafe-2.4.4.jar:2.4.4]
web3signer_latest  |    at tech.pegasys.web3signer.slashingprotection.validator.GenesisValidatorRootValidator.checkGenesisValidatorsRootAndInsertIfEmpty(GenesisValidatorRootValidator.java:46) ~[web3signer-slashing-protection-23.3.1.jar:23.3.1]
web3signer_latest  |    at tech.pegasys.web3signer.slashingprotection.DbSlashingProtection.maySignAttestation(DbSlashingProtection.java:164) ~[web3signer-slashing-protection-23.3.1.jar:23.3.1]
web3signer_latest  |    at tech.pegasys.web3signer.core.service.http.handlers.signing.eth2.Eth2SignForIdentifierHandler.maySign(Eth2SignForIdentifierHandler.java:191) ~[web3signer-core-23.3.1.jar:23.3.1]
web3signer_latest  |    at tech.pegasys.web3signer.core.service.http.handlers.signing.eth2.Eth2SignForIdentifierHandler.signWithSlashingProtection(Eth2SignForIdentifierHandler.java:153) ~[web3signer-core-23.3.1.jar:23.3.1]
web3signer_latest  |    at tech.pegasys.web3signer.core.service.http.handlers.signing.eth2.Eth2SignForIdentifierHandler.lambda$handle$0(Eth2SignForIdentifierHandler.java:119) ~[web3signer-core-23.3.1.jar:23.3.1]
web3signer_latest  |    at tech.pegasys.web3signer.core.service.http.handlers.signing.eth2.Eth2SignForIdentifierHandler$$Lambda$1121/0x0000000800767d78.accept(Unknown Source) ~[?:?]
web3signer_latest  |    at java.util.Optional.ifPresentOrElse(Unknown Source) ~[?:?]
web3signer_latest  |    at tech.pegasys.web3signer.core.service.http.handlers.signing.eth2.Eth2SignForIdentifierHandler.handleSigning(Eth2SignForIdentifierHandler.java:138) ~[web3signer-core-23.3.1.jar:23.3.1]
web3signer_latest  |    at tech.pegasys.web3signer.core.service.http.handlers.signing.eth2.Eth2SignForIdentifierHandler.handle(Eth2SignForIdentifierHandler.java:114) ~[web3signer-core-23.3.1.jar:23.3.1]
web3signer_latest  |    at tech.pegasys.web3signer.core.service.http.handlers.signing.eth2.Eth2SignForIdentifierHandler.handle(Eth2SignForIdentifierHandler.java:58) ~[web3signer-core-23.3.1.jar:23.3.1]
web3signer_latest  |    at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48) ~[vertx-web-4.3.8.jar:4.3.8]
web3signer_latest  |    at io.vertx.ext.web.impl.BlockingHandlerDecorator$$Lambda$1094/0x0000000800751968.handle(Unknown Source) ~[?:?]
web3signer_latest  |    at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137) ~[vertx-core-4.3.8.jar:4.3.8]
web3signer_latest  |    at io.vertx.core.impl.ContextBase$$Lambda$684/0x0000000800602a50.handle(Unknown Source) ~[?:?]
web3signer_latest  |    at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264) ~[vertx-core-4.3.8.jar:4.3.8]
web3signer_latest  |    at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135) ~[vertx-core-4.3.8.jar:4.3.8]
web3signer_latest  |    at io.vertx.core.impl.ContextBase$$Lambda$681/0x0000000800601f40.run(Unknown Source) ~[?:?]
web3signer_latest  |    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
web3signer_latest  |    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
web3signer_latest  |    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.89.Final.jar:4.1.89.Final]
web3signer_latest  |    at java.lang.Thread.run(Unknown Source) ~[?:?]
```

image
image (1)
image (2)

### PR DESCRIPTION
**Pull request by usmansaleem**
## PR Description
Cache gvr in-memory so that maySign and maySignBlock doesn't hit database on every call as gvr is not meant to change once inserted and loaded.

## Fixed Issue(s)

Fixes #600 
May support: #798 

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: slashing-protection/src/test/java/tech/pegasys/web3signer/slashingprotection/DbSlashingProtectionTest.java
Comment (siladu) [inline slashing-protection/src/test/java/tech/pegasys/web3signer/slashingprotection/DbSlashingProtectionTest.java:1]: Think we should either have a unit specifically for testing the cache, or rename an existing test accordingly

File: slashing-protection/src/main/java/tech/pegasys/web3signer/slashingprotection/DbSlashingProtection.java [hunk 1]
```diff
@@ -295,4 +297,29 @@ public void updateValidatorEnabledStatus(final Bytes publicKey, final boolean en
   private boolean isEnabled(final Handle handle, final int validatorId) {
     return validatorsDao.isEnabled(handle, validatorId);
   }
+
+  private boolean isNotValidGVR(final Bytes32 genesisValidatorsRoot) {
```
[the remark this answers is not in the document]
Comment (siladu) [reply slashing-protection/src/main/java/tech/pegasys/web3signer/slashingprotection/DbSlashingProtection.java:301]: Maybe the cache should live with the validator?

**Review by siladu — COMMENTED** [review]
Added some comments, and realised afterwards that I think it would be better if the cache lived in the Validator rather than DbSlashingProtection, which may invalidate some of my comments.

File: slashing-protection/src/main/java/tech/pegasys/web3signer/slashingprotection/DbSlashingProtection.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (usmansaleem) [reply slashing-protection/src/main/java/tech/pegasys/web3signer/slashingprotection/DbSlashingProtection.java:301]: My initial thought was that the gvr is "unique" with respective to DBSlashingProtection, however, on the second thought, it can live in GVRValidator as well.

[the remark this answers is not in the document]
Comment (jframe) [reply slashing-protection/src/main/java/tech/pegasys/web3signer/slashingprotection/DbSlashingProtection.java:301]: Agree with @siladu here, I think the cache should live with the GVRValidator

[the remark this answers is not in the document]
Comment (usmansaleem) [reply slashing-protection/src/main/java/tech/pegasys/web3signer/slashingprotection/DbSlashingProtection.java]: done.

File: slashing-protection/src/test/java/tech/pegasys/web3signer/slashingprotection/DbSlashingProtectionTest.java
Comment (usmansaleem) [reply slashing-protection/src/test/java/tech/pegasys/web3signer/slashingprotection/DbSlashingProtectionTest.java:1]: done

File: slashing-protection/src/main/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidator.java [hunk 2]
```diff
@@ -57,16 +70,15 @@ public boolean genesisValidatorRootExists() {
                 handle -> metadataDao.findGenesisValidatorsRoot(handle).isPresent()));
   }
 
-  private boolean validateGvr(final Handle handle, final Bytes32 genesisValidatorsRoot) {
+  private Void findAndInsertGVR(final Handle handle, final Bytes32 genesisValidatorsRoot) {
```
Comment (siladu) [inline slashing-protection/src/main/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidator.java:73]: Think this is 'Or' not 'And'.

```suggestion
  private Void findOrInsertGVR(final Handle handle, final Bytes32 genesisValidatorsRoot) {
```

File: slashing-protection/src/main/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidator.java [hunk 3]
```diff
@@ -57,16 +70,15 @@ public boolean genesisValidatorRootExists() {
...
-    final boolean isValidGvr = dbGvr.map(gvr -> gvr.equals(genesisValidatorsRoot)).orElse(true);
-    if (!isValidGvr) {
-      LOG.warn(
-          "Supplied genesis validators root {} does not match value in database",
-          genesisValidatorsRoot);
-    } else if (dbGvr.isEmpty()) {
+    if (dbGvr.isPresent()) {
+      cachedGenesisValidatorRoot = dbGvr.get();
+    } else {
+      // insert and update local cache
```
Comment (siladu) [inline slashing-protection/src/main/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidator.java:78]: nit: unnecessary comment

File: slashing-protection/src/main/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidator.java [hunk 4]
```diff
@@ -57,16 +70,15 @@ public boolean genesisValidatorRootExists() {
...
       metadataDao.insertGenesisValidatorsRoot(handle, genesisValidatorsRoot);
+      cachedGenesisValidatorRoot = genesisValidatorsRoot;
     }
-    return isValidGvr;
+    return null;
```
Comment (siladu) [inline slashing-protection/src/main/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidator.java:82]: nit: This feels to me like mixing the cache update with the database stuff. Would it be better to return the gvr and update the cache in the level above?

File: slashing-protection/src/test/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidatorTest.java [hunk 5]
```diff
@@ -23,51 +26,76 @@
...
-    assertThat(
-            gvrValidator.checkGenesisValidatorsRootAndInsertIfEmpty(Bytes32.leftPad(Bytes.of(3))))
+        new GenesisValidatorRootValidator(jdbi, metadataDao);
+    final Bytes32 genesisValidatorsRoot = Bytes32.leftPad(Bytes.of(3));
+    assertThat(gvrValidator.checkGenesisValidatorsRootAndInsertIfEmpty(genesisValidatorsRoot))
+        .isTrue();
+    assertThat(gvrValidator.checkGenesisValidatorsRootAndInsertIfEmpty(genesisValidatorsRoot))
         .isTrue();
+
+    // the database interaction happens for the first call only, cached gvr is used for subsequent
```
Comment (siladu) [inline slashing-protection/src/test/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidatorTest.java:48]: The comments help but do we need to mix testing the cache into all of these unit tests?

**Comment by siladu** [comment]
Just remembered - need a changelog entry?

File: slashing-protection/src/main/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidator.java (hunk 4 above)
Comment (usmansaleem) [reply slashing-protection/src/main/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidator.java]: agreed, refactored the code and renamed the method to convey the intention more clearly as well.

File: slashing-protection/src/main/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidator.java [hunk 6]
```diff
@@ -35,6 +36,8 @@ public class GenesisValidatorRootValidator {
   private final MetadataDao metadataDao;
   private final FailsafeExecutor<Object> failsafeExecutor;
 
+  private Bytes32 cachedGenesisValidatorRoot;
```
[the remark this answers is not in the document]
Comment (usmansaleem) [reply slashing-protection/src/main/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidator.java:39]: correct, we are not too concerned with thread access here.

File: slashing-protection/src/main/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidator.java (hunk 2 above)
Comment (usmansaleem) [reply slashing-protection/src/main/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidator.java]: renamed it to `findAndInsertIfNotExists` which is more clear in the intent.

File: slashing-protection/src/test/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidatorTest.java (hunk 5 above)
Comment (usmansaleem) [reply slashing-protection/src/test/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidatorTest.java]: Agreed. Created specific unit test case to verify cached gvr usage.

**Review by siladu — APPROVED** [review]
Just minor nit 👍

File: CHANGELOG.md [hunk 7]
```diff
@@ -4,6 +4,9 @@
 - Optional Azure bulk loading tags support using cli option `--azure-secrets-tags`.
 - Support Prometheus Push Gateway Metrics [#796](https://github.com/ConsenSys/web3signer/pull/796)
 
+### Performance Enhancements
```
[the remark this answers is not in the document]
Comment (usmansaleem) [reply CHANGELOG.md]: done.

File: slashing-protection/src/test/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidatorTest.java [hunk 8]
```diff
@@ -23,22 +26,46 @@
...
   void checkGenesisValidatorReturnTrueForNewGVR(final Jdbi jdbi) {
     final GenesisValidatorRootValidator gvrValidator =
-        new GenesisValidatorRootValidator(jdbi, new MetadataDao());
-    assertThat(
-            gvrValidator.checkGenesisValidatorsRootAndInsertIfEmpty(Bytes32.leftPad(Bytes.of(3))))
+        new GenesisValidatorRootValidator(jdbi, metadataDao);
+    final Bytes32 genesisValidatorsRoot = Bytes32.leftPad(Bytes.of(3));
+    assertThat(gvrValidator.checkGenesisValidatorsRootAndInsertIfEmpty(genesisValidatorsRoot))
         .isTrue();
   }
```
Comment (jframe) [inline slashing-protection/src/test/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidatorTest.java:46]: Also be good to add a test that shows that is it not cached when we fail insert the GVR due to a database exception

File: slashing-protection/src/test/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidatorTest.java [hunk 9]
```diff
@@ -23,22 +26,46 @@
...
 
+  @Test
```
Comment (jframe) [inline slashing-protection/src/test/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidatorTest.java:47]: There is also the cache where we will cache and not insert if the GVR already exists in the db

File: slashing-protection/src/main/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidator.java [hunk 10]
```diff
@@ -43,10 +46,23 @@ public GenesisValidatorRootValidator(final Jdbi jdbi, final MetadataDao metadata
...
+    if (cachedGenesisValidatorRoot == null) {
+      cachedGenesisValidatorRoot =
+          failsafeExecutor.get(
+              () ->
+                  jdbi.inTransaction(
+                      READ_COMMITTED,
+                      handle -> findAndInsertIfNotExists(handle, genesisValidatorsRoot)));
+    }
+
+    if (Objects.equals(cachedGenesisValidatorRoot, genesisValidatorsRoot)) {
```
Comment (jframe) [inline slashing-protection/src/main/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidator.java:58]: Why we do need to use Object.equals here?

Comment (usmansaleem) [reply slashing-protection/src/main/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidator.java:58]: its to avoid NPE in case cachedGenesisValidatorRoot is still null after the insert call.

File: slashing-protection/src/test/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidatorTest.java (hunk 8 above)
Comment (usmansaleem) [reply slashing-protection/src/test/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidatorTest.java:49]: done

File: slashing-protection/src/test/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidatorTest.java (hunk 9 above)
Comment (usmansaleem) [reply slashing-protection/src/test/java/tech/pegasys/web3signer/slashingprotection/validator/GenesisValidatorRootValidatorTest.java:50]: done

**Review by jframe — APPROVED** [review]
LGTM
