### PR TITLE
[fix] - Fix EIP-712 eth_signTypedData in eth1 mode

### LINKED ISSUE #1012: EIP-712: Support to sign typed data with prefix \x19\x01
EIP-712: https://eips.ethereum.org/EIPS/eip-712

EIP-712 add support to sign typed data. There are three format to encode the data
```
encode(transaction : 𝕋) = RLP_encode(transaction)
encode(message : 𝔹⁸ⁿ) = "\x19Ethereum Signed Message:\n" ‖ len(message) ‖ message
encode(domainSeparator : 𝔹²⁵⁶, message : 𝕊) = "\x19\x01" ‖ domainSeparator ‖ hashStruct(message)
```

#893 add support to sign typed data, but the [documentation](https://docs.web3signer.consensys.io/reference/api/json-rpc#eth_signtypeddata) states it signs with prefix `\x19Ethereum Signed Message:\n`

Running the curl command given in documentation, gives the following error.
### Command
```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_signTypedData","params":["0xCD2a3d9F938E13CD947Ec05AbC7FE734Df8DD826", {"types":{"EIP712Domain":[{"name":"name","type":"string"},{"name":"version","type":"string"},{"name":"chainId","type":"uint256"},{"name":"verifyingContract","type":"address"}],"Person":[{"name":"name","type":"string"},{"name":"wallet","type":"address"}],"Mail":[{"name":"from","type":"Person"},{"name":"to","type":"Person"},{"name":"contents","type":"string"}]},"primaryType":"Mail","domain":{"name":"Ether Mail","version":"1","chainId":1,"verifyingContract":"0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC"},"message":{"from":{"name":"Cow","wallet":"0xCD2a3d9F938E13CD947Ec05AbC7FE734Df8DD826"},"to":{"name":"Bob","wallet":"0xbBbBBBBbbBBBbbbBbbBbbbbBBbBbbbbBbBbbBBbB"},"contents":"Hello, Bob!"}}],"id":1}' http://localhost:9000
```
#### Result
```
{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"Internal error"}}
```

Does the web3signer, supports 3rd format with prefix `\x19\x01`?

### PR DESCRIPTION
**Pull request by usmansaleem**
## PR Description
Fix parsing of structured data for `eth_signTypedData`.

Example of how to perform sign typed data validation using Ethers.js https://github.com/usmansaleem/signers_docker_compose/blob/main/web3signer-eth1/signing-test/testTypedData.js

## Fixed Issue(s)

fixes #1012 

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

## Testing

- [x] I thought about testing these changes in a realistic/non-local environment.

### CODE REVIEW

File: signing/src/main/java/tech/pegasys/web3signer/signing/util/IdentifierUtils.java [hunk 1]
```diff
@@ -17,6 +17,9 @@
 public class IdentifierUtils {
 
   public static String normaliseIdentifier(final String signerIdentifier) {
+    if (signerIdentifier == null) {
```
Comment (jframe) [inline signing/src/main/java/tech/pegasys/web3signer/signing/util/IdentifierUtils.java]: why would we have a null signerIdentifier?

Comment (usmansaleem) [reply signing/src/main/java/tech/pegasys/web3signer/signing/util/IdentifierUtils.java]: you are correct, I'll remove this check. I added it on the spur of the moment.

**Review by jframe — APPROVED** [review]
